name: MeteoCaos
on:
  workflow_dispatch:
  
  schedule:
    - cron: '10 6 * * *'
      timezone: 'America/Sao_Paulo'
    - cron: '10 9 * * *'
      timezone: 'America/Sao_Paulo'
    - cron: '10 12 * * *'
      timezone: 'America/Sao_Paulo'
    - cron: '10 15 * * *'
      timezone: 'America/Sao_Paulo'
    - cron: '10 18 * * *'
      timezone: 'America/Sao_Paulo'
    - cron: '10 21 * * *'
      timezone: 'America/Sao_Paulo'

jobs:
 executar:
    runs-on: ubuntu-latest
    steps:
    - name: Baixar código
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v5
      with: 
        python-version: '3.12'

    - name: Instalar dependências
      run: pip install -r requirements.txt

    - name: Executar MeteoCaos
      env:
        NTFY_TOPIC: ${{secrets.NTFY_TOPIC}}
      run: python meteocaos.py
        
